min_trimmed_length = 3
min_word_count = 4
max_word_count = 14
min_characters = 2
may_end_with_colon = false
quote_start_with_letter = true
needs_punctuation_end = true
needs_letter_start = true
needs_uppercase_start = true
#alphabet without the letters q, w, x and y
allowed_symbols_regex="[AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpRrSsTtUuVvZzĉĈĝĜĥĤĵĴŝŜŭŬ;‚'–\\. \"\\?!«»()]"
broken_whitespace = ["  ", " ,", " .", " ?", " !", " ;"]
matching_symbols = [
  ["„", "“"],
  ["(", ")"]
]

# Abbreviation examples for each regex, also cheating a bit and adding more regex which has nothing to do with abbreviations:
#   - A.B or z.B.
#   - kaj tiel plu, Volumo, ekzemple,... see https://eo.wikipedia.org/wiki/Mallongigo
#   - No words with only one letter (" a.", " a", " a ", "a ")
#   - Mixed upper/lowercase in words (LaSi - mostly chemical elements?)
#   - letter combinations that are hard to pronounce or very rare in Esperanto and only used in other languages
abbreviation_patterns = [
  "[A-Z]+\\.*[A-Z]",
  "ktp\\.|k\\.t\\.p\\.|[E|e]kz\\.|inkl\\.|[I|i]nĝ\\.|str\\.|Str\\.|ca\\.|[T|t]rad\\.|[E|e]ld\\.|[V|v]ol\\.|mag\\.|red\\.|prez\\.|proks\\.|gem\\.|[a|p]\\.\\sK\\.|[P|p]rof\\.|Ak\\.|anst\\.|bv\\.|k\\.|k\\.a\\.|k\\.c\\.|p\\.|v\\.|ĉ\\.|i\\.a\\.|t\\.n\\.|t\\.e\\.",
  "(\\s[A-Za-z]{1}[\\.|\\?|!]*$)|(^[A-Za-z]{1}\\s)|\\s[A-Za-z]{1}\\s",
  "[a-z][A-Z][a-z]",
  "sch","Sch","sh","Sh","ch","Ch","cc","Cc","the","The","ingen","ille","eau","our",
  
]
